def re_decoder(variable):
    variable = variable.replace("[", "\[")
    variable = variable.replace("]", "\]")
    variable = variable.replace(".", "\.")
    variable = variable.replace("*", "\*")
    variable = variable.replace("^", "\^")
    variable = variable.replace("$", "\$")
    variable = variable.replace("+", "\+")
    variable = variable.replace("?", "\?")
    variable = variable.replace("{", "\{")
    variable = variable.replace("}", "\}")
    variable = variable.replace("|", "\|")
    variable = variable.replace("(", "\(")
    variable = variable.replace(")", "\)")
    variable = variable.replace("\A", "\\A")
    variable = variable.replace("\b", "\\b")
    variable = variable.replace("\B", "\\B")
    variable = variable.replace("\d", "\\d")
    variable = variable.replace("\D", "\\D")
    variable = variable.replace("\s", "\\s")
    variable = variable.replace("\S", "\\S")
    variable = variable.replace("\w", "\\w")
    variable = variable.replace("\W", "\\W")
    variable = variable.replace("\Z", "\\Z")
    return variable