#!/bin/sh

set -e

chmod 4755 /opt/MeeShop/main.py

source /tmp/session_bus_address.user
dbus-send --print-reply --dest=com.meego.core.MNotificationManager /notificationmanager com.meego.core.MNotificationManager.addNotification uint32:1000 uint32:0 string:'custom' string:'MeeShop' string:'MeeShop v0.2.0 installed successfully.' string:'' string:'/usr/share/icons/hicolor/80x80/apps/MeeShop80.png' uint32:0 > /dev/null

exit 0
